name: audio_relay_x_client
description: Fully Open Source Local Network Audio Relay
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap:
    git:
      url: https://github.com/AudioRelayXX/app_bootstrap
      ref: master
  tapper:
    git:
      url: https://github.com/AudioRelayXX/tapper
      ref: master
  framer:
    git:
      url: https://github.com/AudioRelayXX/framer
      ref: master
  forge:
    git:
      url: https://github.com/AudioRelayXX/forge
      ref: master
  trebuchet:
    git:
      url: https://github.com/AudioRelayXX/trebuchet
      ref: master
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true